TrainingCenter/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Entities;
using DAL.Repositories;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using TMS.Core.App_GlobalResources;
using TMS.Core.Services.Approves;
using TMS.Core.Services.Configs;
using TMS.Core.Services.CourseDetails;
using TMS.Core.Services.CourseMember;
using TMS.Core.Services.Courses;
using TMS.Core.Services.Department;
using TMS.Core.Services.Employee;
using TMS.Core.Services.Notifications;
using TMS.Core.Services.Users;
using TMS.Core.Utils;
using TMS.Core.ViewModels;
using TMS.Core.ViewModels.APIModels;
using TMS.Core.ViewModels.Common;
using TMS.Core.ViewModels.Survey;
using TMS.Core.ViewModels.Courses;
using TMS.Core.ViewModels.Room;
using Utilities;
using TrainingCenter.Serveices;
using static TrainingCenter.Controllers.SurveyController;
using static TrainingCenter.Controllers.ReminderController;
using DAL.UnitOfWork;
using TrainingCenter.Utilities;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using AppUtils = Utilities.AppUtils;
using System.Threading.Tasks;
using System.Globalization;
//using TrainingCenter.Serveices;

namespace TrainingCenter.Controllers
{
    public class SurveyController : BaseAdminController
    {
        // GET: Survey
        #region init
        private readonly IRepository<MENU> _repoMenu = null;
        private readonly IRepository<Course> _repoCourse = null;
        private readonly IRepository<Room> _repoRoom = null;
        private readonly CallLmsServices _sLmsServices = null;
        private readonly IRepository<Trainee> _repoTrainee = null;
        private readonly IRepository<TMS_Course_Member> _repoCourse_Member = null;
        private readonly IRepository<Course_Detail_Instructor> _repoCourse_detail_instructor;

        private readonly IRepository<Course_Detail> _repoCourse_Detaillist = null;

        public SurveyController(IRepository<Course_Detail_Instructor> repoCourse_detail_instructor, IRepository<TMS_Course_Member> repoCourse_Member, IRepository<Trainee> repoTrainee, IConfigService configService, IUserContext userContext, INotificationService notificationService, ICourseMemberService courseMemberService, IEmployeeService employeeService, ICourseDetailService courseDetailService, IDepartmentService departmentService, ICourseService courseService, IApproveService approveService, IRepository<MENU> repoMenu, IRepository<Course> repoCourse, IRepository<Room> repoRoom, /*CallLmsServices sLmsServices,*/ IRepository<Course_Detail> repoCourse_Detaillist) : base(configService, userContext, notificationService, courseMemberService, employeeService, courseDetailService, departmentService, courseService, approveService)
        {
            _repoCourse_Member = repoCourse_Member;
            _repoTrainee = repoTrainee;
            _repoMenu = repoMenu;
            _repoCourse = repoCourse;
            _repoRoom = repoRoom;
            _repoCourse_detail_instructor = repoCourse_detail_instructor;
            _sLmsServices = new CallLmsServices();
            _repoCourse_Detaillist = repoCourse_Detaillist;
        }

        public class ServicesResultModel
        {
            public string TenHam { get; set; }
            public List<RootObject> Lms { get; set; }

        }
        public class UserSurvey
        {
            public string userid { get; set; }
            public string username { get; set; }
            public int idTrainee { get; set; }
            public int IdcCourse { get; set; }
            public string score { get; set; }
            public string result { get; set; }
            //
            public string fullname { get; set; }
            public string department { get; set; }

            //public string remark { get; set; }
            public List<Response_rank> response_rank { get; set; }
            public List<Response_text> response_text { get; set; }

        }
        public class Choise
        {
            public string content { get; set; }
        }
        public class Question
        {
            public string name { get; set; }
            public string name_type { get; set; }
            public string content { get; set; }
            public List<Choise> choise { get; set; }
        }
        public class Response_rank
        {
            public string response_id { get; set; }
            public string question_id { get; set; }
            public string choice_id { get; set; }
            public string rank { get; set; }
        }

        public class Response_text
        {
            public string response_id { get; set; }
            public string question_id { get; set; }
            public string response { get; set; }
        }

        public class RootObject
        {
            public string course_code { get; set; }
            public string code_survey { get; set; }
            public string name { get; set; }
            public string intro { get; set; }
            public List<UserSurvey> users { get; set; }
            public List<Question> question { get; set; }
            public int? id_survey { get; set; }

        }
        public class user
        {
            public string userid { get; set; }
            public string username { get; set; }
            public int idTrainee { get; set; }
            public int IdcCourse { get; set; }
            public string score { get; set; }
            public string result { get; set; }
            //
            public string fullname { get; set; }
            public string department { get; set; }

            //public string remark { get; set; }
            public List<Response_rank> response_rank { get; set; }
            public List<Response_text> response_text { get; set; }

        }
        public class SurveyViewModel
        {
            public int? Survey_ID { get; set; }
            public int? CourseDetail_ID { get; set; }
            public string Course_Name { get; set; }
            public string Course_Code { get; set; }
            public string Survey_Name { get; set; }
            public string Subject_Code { get; set; }
            public string Subject_Name { get; set; }
            public string Date_From { get; set; }
            public string Date_To { get; set; }
            public DateTime Date_FromDT { get; set; }
            public DateTime Date_ToDT { get; set; }
        }
        [AllowAnonymous]
        public ActionResult AjaxHandleListSurvey(jQueryDataTableParamModel param)
        {
            try
            {
                System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("vi-VN");
                IFormatProvider culture = new System.Globalization.CultureInfo("vi-VN", true);
                #region [Lấy dữ liệu LMS]

                var suurvey_model = new List<SurveyViewModel>();
                var model = new List<RootObject>();
                var type = UtilConstants.CRON_POST_SURVEY;
                var server = GetByKey("API_LMS_SERVER");
                var token = GetByKey("API_LMS_TOKEN");
                var function = GetByKey("FUNCTION");
                var moodlewsrestformat = GetByKey("moodlewsrestformat") ?? "";
                var restClient = new RestClient(server);
                var request = new RestRequest(Method.POST);
                request.AddParameter("wstoken", token);

                request.AddParameter("wsfunction", function);
                request.AddParameter("moodlewsrestformat", moodlewsrestformat);
                request.AddParameter("type", type);
                var response = restClient.Execute(request);
                var responseContent = response.Content;
                //model = JsonConvert.DeserializeObject<List<RootObject>>(response.Content);
                IEnumerable<UserSurvey> filtesred = new List<UserSurvey>();

                if (responseContent.Contains("\"warnings\":[]") || responseContent.Contains("\"exception\":[]"))
                {
                    var num = responseContent.IndexOf("###################################################");
                    responseContent = responseContent.Remove(num);
                    var model_ = JsonConvert.DeserializeObject<List<ServicesResultModel>>(responseContent);
                    model = model_?.FirstOrDefault()?.Lms;
                    if (model != null)
                    {
                        foreach (var item in model)
                        {
                            var survey_item = new SurveyViewModel();
                            survey_item.Survey_ID = item?.id_survey ?? -1;
                            survey_item.Survey_Name = "<span data-value='" + survey_item.Survey_ID + "' class='expand' style='cursor: pointer;'><a>" + item?.name + "</a></span>";
                            if (!string.IsNullOrEmpty(item?.course_code))
                            {
                                //var courseDetailID = item?.course_code?.Split('_');
                                var courseDetail_value = ""; //courseDetailID[1];
                                var checkcode = item?.course_code?.LastIndexOf("::");
                                if (checkcode != -1)
                                {
                                    courseDetail_value = item?.course_code?.Substring((int)checkcode + 2);
                                }

                                var record = _repoCourse_Detaillist.Get(Convert.ToInt32(courseDetail_value));
                                survey_item.CourseDetail_ID = record?.Id;
                                survey_item.Subject_Name = record?.SubjectDetail?.Name;
                                survey_item.Subject_Code = record?.SubjectDetail?.Code;
                                survey_item.Date_From = DateUtil.DateToString(record?.dtm_time_from, "dd/MM/yyyy");

TrainingCenter/Views/Survey/Modify.cshtml
@using TMS.Core.Utils
@using TMS.Core.App_GlobalResources
@model TMS.Core.ViewModels.Survey.SurveyModels
@{
    ViewBag.Title = "Modify";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fab fa-keycdn"></i>  Survey Management - @(Model.Id == 0? "Create" : "Edit")</h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li>Survey Management</li>
                <li class="active">@(Model.Id == 0 ? "Create" : "Edit")</li>
            </ol>
        </div>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="panel list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title"><i class="fas fa-pencil-alt font-small-byhoa" aria-hidden="true"></i> @(Model.Id == 0 ? "Create" : "Edit")</h1>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Modify", "Survey", FormMethod.Post, new { @class = "form-horizontal bordered-row", id = "createform" }))
            {
                @Html.AntiForgeryToken()

                @Html.HiddenFor(model => model.Id)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-4">
                                <label>@Resource.lblCode <span class="text-danger">(*)</span></label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" id="Code" name="Code" @(Model.Id == null ? "" : "readonly" ) value="@Model.Code" data-parsley-required-message="Required Fields" required class="form-control">
                                @Html.ValidationMessageFor(m => m.Code, null, new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-4">
                                <label>@Resource.lblName <span class="text-danger">(*)</span> </label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" id="Name" name="Name" value="@Model.Name" data-parsley-required-message="Required Fields" required class="form-control">
                                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-4">
                                <label>@Resource.lblStartDate<span class="text-danger">(*)</span></label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" class="form-control pull-right frmFilter" name="StartDate" id="StartDate" placeholder="@Resource.lblStartDate" value="@Model.StartDate">
                                </div>

                                @Html.ValidationMessageFor(m => m.StartDate, null, new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-4">
                                <label>@Resource.lblEndDate<span class="text-danger">(*)</span></label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" class="form-control pull-right frmFilter" name="EndDate" id="EndDate" placeholder="@Resource.lblEndDate" value="@Model.EndDate">
                                </div>
                                @Html.ValidationMessageFor(m => m.EndDate, null, new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group row">
                            <div class="col-md-2">
                                <label> @Resource.lblDescription</label>
                            </div>
                            <div class="col-md-10">
                                <textarea class="form-control" cols="20" name="Description" id="Description" rows="2">@Model.Description</textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-4">
                                <label> Visible</label>
                            </div>
                            <div class="col-md-8">
                                <select class="form-control" id="IsActive" name="IsActive">
                                    <option value="true">Show</option>
                                    <option value="false">Hiden</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
        }
                <div class="row">
                    <div class="action-form text-right">
                        @{
                        if (User.IsInRole("/Contract/Modify"))
                        {
                            <a href="javascript:void(0)" class="btn btn-primary  legitRipple" id="submit" onclick=" submit() "><i class="fas fa-save" aria-hidden="true"></i> @Resource.lblSave</a>
                            <a onclick=" goBack() " class="btn  btn-default legitRipple"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> @Resource.lblBack</a>
                    }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{

    <script type="text/javascript">
            $(document).ready(function() {
                $('.date').datetimepicker({
                    format: "HH:mm"
                });
                formatDatetimepicker('#StartDate', '@Resource.lblLanguage');

                formatDatetimepicker('#EndDate', '@Resource.lblLanguage');
            });

            function submit() {
                spinner.open();
                $('#submit').hide();
                var form = document.getElementById('createform');
                var formData = new FormData(form);

                $.ajax({
                    type: 'POST',
                    url: "/Survey/Modify",
                    contentType: false,
                    processData: false,
                    data: formData,
                    //datatype: 'json',
                    success: function (data) {
                        if (!data.result) {
                            notify.alert(data.message, "WARNING", TITLE_STATUS_DANGER);
                        } else {
                            notify.alert(data.message, "SUCCESS", TITLE_STATUS_SUCCESS);
                            window.location.href = "/Survey/Index/";
                        }
                    },
                    complete: function () {
                        spinner.close();
                        $('#submit').show();
                    }
                });
            }
    </script>
}