TrainingCenter/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using TrainingCenter.Utilities;
using DAL.Entities;
using TMS.Core.Services.Configs;
using TMS.Core.Services.Contracts;
using TMS.Core.Services.CourseDetails;
using TMS.Core.Services.CourseMember;
using TMS.Core.Services.Employee;
using TMS.Core.Services.Notifications;
using TMS.Core.Services.Users;
using TMS.Core.App_GlobalResources;
using TMS.Core.Services.Approves;
using TMS.Core.Utils;

namespace TrainingCenter.Controllers
{
    using OfficeOpenXml;
    using OfficeOpenXml.Style;
    using Resources;
    using System.Configuration;
    using System.Data.Entity.SqlServer;
    using System.Globalization;
    using System.IO;
    using System.Text.RegularExpressions;
    using TMS.Core.Services;
    using TMS.Core.Services.Courses;
    using TMS.Core.Services.Department;
    using TMS.Core.ViewModels;
    using TMS.Core.ViewModels.Common;
    using TMS.Core.ViewModels.Contracts;

    public class ContractController : BaseAdminController
    {
        #region MyRegion

        private readonly IContractService _repoContract;



        #endregion

        public ContractController(IConfigService configService, IUserContext userContext, INotificationService notificationService, ICourseMemberService courseMemberService, IEmployeeService employeeService, ICourseDetailService courseDetailService, IDepartmentService departmentService, ICourseService courseService, IContractService repoContract, IApproveService approveService) : base(configService, userContext, notificationService, courseMemberService, employeeService, courseDetailService, departmentService, courseService, approveService)
        {
            _repoContract = repoContract;
        }

        #region Export EXCEL
        public FileResult ExportEXCEL(FormCollection form)
        {
            var filecontent = ExportEXCEL();
            if (filecontent != null)
            {
                return File(filecontent, ExportUtils.ExcelContentType, "Contract_List.xlsx");
            }
            return null;
        }
        private byte[] ExportEXCEL()
        {
            System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("vi-VN");
            IFormatProvider culture = new System.Globalization.CultureInfo("vi-VN", true);
            string templateFilePath = Server.MapPath(@"" + GetByKey("PrivateTemplate") + "/Template/ExcelFile/Contract_List.xlsx");
            FileInfo template = new FileInfo(templateFilePath);
            //var courseDetail = _repoCourseServiceDetail.GetById(ddlSubject);

            int Contractor2 = string.IsNullOrEmpty(Request.QueryString["Contractor2"]) ? -1 : Convert.ToInt32(Request.QueryString["Contractor2"].Trim());
            int Status2 = string.IsNullOrEmpty(Request.QueryString["Status2"]) ? -1 : Convert.ToInt32(Request.QueryString["Status2"]);
            int Type2 = string.IsNullOrEmpty(Request.QueryString["Type2"]) ? -1 : Convert.ToInt32(Request.QueryString["Type2"]);
            string str_Code2 = string.IsNullOrEmpty(Request.QueryString["str_Code2"]) ? "" : Request.QueryString["str_Code2"].Trim();
            string str_Contractno2 = string.IsNullOrEmpty(Request.QueryString["str_Contractno2"]) ? "" : Request.QueryString["str_Contractno2"].Trim();
            string url = string.IsNullOrEmpty(Request.QueryString["url"]) ? string.Empty : Request.QueryString["url"].ToLower().Trim();

            var data = _repoContract.Get(a =>
            (Contractor2 == -1 || a.int_Id_contractor == Contractor2) &&
            (Status2 == -1 || a.int_Id_status == Status2) &&
            (Type2 == -1 || a.int_Id_type == Type2) &&
            (string.IsNullOrEmpty(str_Code2) || a.str_Code.Contains(str_Code2)) &&
            (string.IsNullOrEmpty(str_Contractno2) || a.str_Contractno.Contains(str_Contractno2))
             ).OrderByDescending(a => a.id);

            ExcelPackage excelPackage;
            MemoryStream ms = new MemoryStream();
            byte[] bytes = null;
            if (data != null)
            {
                using (excelPackage = new ExcelPackage(template, false))
                {
                    ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.First();
                    int startRow = 9;
                    //var Row = 0;
                    int count = 0;
                    foreach (var item in data)
                    {
                        int col = 2;
                        count++;
                        ExcelRange cellNo = worksheet.Cells[startRow + 1, col];
                        cellNo.Value = count;
                        cellNo.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                        cellNo.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellNo.Style.Border.BorderAround(ExcelBorderStyle.Thin);


                        ExcelRange cellCode = worksheet.Cells[startRow + 1, ++col];
                        cellCode.Value = item?.str_Code;
                        cellCode.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                        cellCode.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellCode.Style.Border.BorderAround(ExcelBorderStyle.Thin);


                        ExcelRange cellContrctNo = worksheet.Cells[startRow + 1, ++col];
                        cellContrctNo.Value = item?.str_Contractno;
                        cellContrctNo.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                        cellContrctNo.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellContrctNo.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        ExcelRange cellCONTRACTOR = worksheet.Cells[startRow + 1, ++col];
                        cellCONTRACTOR.Value = item?.CAT_CONTRACTOR?.str_Fullname ?? "";
                        cellCONTRACTOR.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellCONTRACTOR.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                        cellCONTRACTOR.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        ExcelRange cellPrice = worksheet.Cells[startRow + 1, ++col];
                        cellPrice.Value = item.mon_Price.HasValue ? item?.mon_Price.Value.ToString("N", culture) + (item.Currency.HasValue? " "+ UtilConstants.CurrencyDictionary()[item.Currency.Value].ToString() : "") : "0";
                        cellPrice.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellPrice.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                        cellPrice.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        ExcelRange cellExpiryDate = worksheet.Cells[startRow + 1, ++col];
                        cellExpiryDate.Value = item?.dtm_Expiredate != null ? DateUtil.DateToString(item?.dtm_Expiredate, "dd/MM/yyyy") : "";
                        cellExpiryDate.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellExpiryDate.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                        cellExpiryDate.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        ExcelRange cellPhone = worksheet.Cells[startRow + 1, ++col];
                        cellPhone.Value = item?.CAT_CONTRACTS_STATUS?.name;
                        cellPhone.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellPhone.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                        cellPhone.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        ExcelRange cellActive = worksheet.Cells[startRow + 1, ++col];
                        cellActive.Value = item?.bit_Is_active == true ? "Active" : "DeActive";
                        cellActive.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                        cellActive.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                        cellActive.Style.Border.BorderAround(ExcelBorderStyle.Thin);

                        startRow++;

                    }
                    bytes = excelPackage.GetAsByteArray();
                }

            }
            return bytes;

        }

        #endregion

        public ActionResult Index(int id = 0)
        {
            var model = new ContractModels
            {

                Contractor = _repoContract.GetContractList(),
                Type = _repoContract.GetContractType(),
                Status = _repoContract.GetContractStatus(),
            };
            return View(model);
        }


        public ActionResult Modify(int id = 0, string type = "")
        {
            System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("vi-VN");
            IFormatProvider culture = new System.Globalization.CultureInfo("vi-VN", true);
            var model = new ContractModels();

            if (id != 0)
            {
                var entity = _repoContract.GetById(id);
                model.Id = entity.id;
                model.ContractorID = entity.int_Id_contractor;
                model.Code = entity.str_Code;
                model.ContractNO = entity.str_Contractno;
                model.Description = entity.str_Description;
                model.SignDate = entity.dtm_Signdate;
                model.Expiredate = entity.dtm_Expiredate;
                model.Note = entity.str_Note;
                model.Price = entity.mon_Price;
                model.Currency = entity.Currency;
                model.StatusID = entity.int_Id_status;
                model.TypeID = entity.int_Id_type;
                model.CreatedDate = entity.dtm_Created_date;
                model.UpdateDate = entity.dtm_Last_updated_date;
            }
            ViewBag.id = id;
            ViewBag.mModel = model;

TrainingCenter/Views/Contract/Createpage.cshtml
@using TMS.Core.App_GlobalResources
@using TMS.Core.Utils
@model TMS.Core.ViewModels.Contracts.ContractModels
@{
    ViewBag.Title = "Modify";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section breadcrumb{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fab fa-keycdn"></i> @Resource.lblContractManagement - @Resource.lblCreate</h1>
            <ol class="breadcrumb">
                <li><a href="/">@Resource.lblHome</a></li>
                <li><a href="/Contract/Index">@Resource.lblContractManagement</a> </li>
                <li class="active">@Resource.lblCreate</li>
            </ol>
        </div>
    </div>
}

<div class="panel list-panel" id="list-panel">
    <div class="panel-heading list-panel-heading">
        <h1 class="panel-title list-panel-title"><i class="fas fa-pencil-alt font-small-byhoa" aria-hidden="true"></i> @Resource.lblCreate </h1>
    </div>
    <div class="panel-body center-block">
        @using (Html.BeginForm("Modify", "Contract", FormMethod.Post, new { id = "createform" }))
        {
            @Html.AntiForgeryToken()
            @*<input type="hidden" id="hd_id" name="id" value="@Model.Id" />*@
            <div class="row">
                @Html.HiddenFor(model => model.Id)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group col-md-6">
                    <label>@Resource.lblContractor </label>
                    @Html.DropDownListFor(m => m.ContractorID, new SelectList(Model.ContractorList.OrderBy(a => a.Value), "Key", "Value", Model.ContractorID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Contractor--" }, { "onchange", "ChangeCode()" } })
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblCode <font color="red">(*)</font></label>
                    <input type="text" id="str_Code" name="str_Code" value="@Model.Code" data-parsley-required-message="Required Fields" required class="form-control" readonly="readonly">
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblContractNo <font color="red">(*)</font></label>
                    <input type="text" name="str_Contractno" value="@Model.ContractNO" class="form-control">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label>@Resource.lblDescription </label>
                    <input type="text" name="str_Description" value="@Model.Description" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblSignDate <font color="red">(*)</font></label>
                    <input type="text" id="dtm_Signdate" name="dtm_Signdate" value="@(Model.SignDate != null ? Model.SignDate.Value.ToString() : "")" class="form-control date-picker" required>
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblExpireDate <font color="red">(*)</font></label>
                    <input type="text" id="dtm_Expiredate" name="dtm_Expiredate" value="@(Model.Expiredate != null ? Model.Expiredate.Value.ToString() : "")" class="form-control date-picker" required onclick=" check() ">
                </div>
            </div>
            <div class="row">                
                <div class="form-group col-md-3">
                    <label>@Resource.lblStatus </label>
                    @Html.DropDownListFor(m => m.StatusID, new SelectList(Model.StatusList, "Key", "Value", Model.StatusID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Status--" } })
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblPrice </label>
                    <input type="number" name="mon_Price" value="@Model.Price" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblCurrency </label>
                    @Html.DropDownListFor(m => m.Currency, new SelectList(Model.Curencylist, "Key", "Value", Model.Currency), new { @class = "form-control" })
                </div>
                <div class="form-group col-md-3">
                    <label>@Resource.lblType </label>
                    @Html.DropDownListFor(m => m.TypeID, new SelectList(Model.TypeList, "Key", "Value", Model.TypeID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Type--" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label>@Resource.lblNote</label>
                    <textarea name="str_Note" value="@Model.Note" class="form-control" rows="3"></textarea>
                </div>
            </div>
            <div class="divider"></div>
            <div class="divider"></div>
            <div class="form-group col-lg-12">
                <div id="messageout">
                </div>
            </div>
        }
        <div class="row">
            <div class="action-form text-right">
                @{
                    if (User.IsInRole("/Contract/Modify"))
                    {
                        <a href="javascript:void(0)" class="btn btn-primary legitRipple" id="submit" onclick=" submit() "><i class="fas fa-save" aria-hidden="true"></i> @Resource.lblSave</a>
                        <a onclick=" goBack() " class="btn btn-default legitRipple"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> @Resource.lblBack</a>
                    }
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            ChangeCode();
            formatDatetimepicker('.date-picker', '@Resource.lblLanguage');
        });

        function check() {

            var minDate = $("#dtm_Signdate").data('DateTimePicker').date().startOf('day');
            $('#dtm_Expiredate').data("DateTimePicker").minDate(minDate);

        }
        //function check1() {

        //    var maxDate = $("#dtm_Expiredate").data('DateTimePicker').date().startOf('day');
        //    $('#dtm_Signdate').data("DateTimePicker").maxDate(maxDate);

        //}
        function submit() {
            spinner.open();
            var form = $("#createform").serialize();
            $.ajax({
                type: 'POST',
                url: "/Contract/Modify",
                datatype: 'json',
                data: form,
                success: function (data) {
                    if (data.result) {
                        notify.alert(data.message, 'Success', TITLE_STATUS_SUCCESS);
                        window.location.href = '/Contract';
                    }
                    else {
                        notify.alert(data.message, 'Error', TITLE_STATUS_DANGER);
                    }
                }
                , complete: function () {
                    spinner.close();
                }
            });
        }
        function ChangeCode() {
            var valuetype = $("#ContractorID").val();
            $.ajax({
                type: 'POST',
                url: "/Contract/GenerateCode",
                datatype: 'json',
                data: { valuetype: valuetype },
                success: function (data) {
                    $("#str_Code").val(data);
                }
            });
        }
    </script>
}

TrainingCenter/Views/Contract/Detailpage.cshtml
@using TMS.Core.App_GlobalResources
@using TMS.Core.Utils
@model TMS.Core.ViewModels.Contracts.ContractModels

@section breadcrumb{
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><i class="fa fa-file-signature"></i> @Resource.lblContractManagement - @Resource.lblDetails</h1>
            <ol class="breadcrumb">
                <li><a href="/">@Resource.lblHome</a></li>
                <li> @Resource.lblContractManagement</li>
                <li class="active">@Resource.lblDetails</li>
            </ol>
        </div>
    </div>
}

<div id="Detail-contract">
    <div class="panel list-panel" id="list-panel">
        <div class="panel-heading list-panel-heading">
            <h1 class="panel-title list-panel-title"><i class="fas fa-list font-small-byhoa" aria-hidden="true"></i> @Resource.lblDetails </h1>
        </div>
        <div class="panel-body center-block">
            @using (Html.BeginForm("Modify", "Contract", FormMethod.Post, new { id = "createform" }))
            {
                <input type="hidden" id="hd_id" name="id" value="@Model.Id" />
                <div class="row">
                    <div class="form-group col-md-4">
                        <label>@Resource.lblCode </label>
                        <input disabled type="text" id="str_Code" name="str_Code" value="@Model.Code" data-parsley-required-message="Required Fields" required class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblContractor </label>
                        @Html.DropDownListFor(m => m.ContractorID, new SelectList(Model.ContractorList, "Key", "Value", Model.ContractorID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Contractor--" }, { "disabled", "true" } })
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblContractNo </label>
                        <input disabled type="text" name="str_Contractno" value="@Model.ContractNO" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label>@Resource.lblDescription </label>
                        <input disabled type="text" name="str_Description" value="@Model.Description" class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblSignDate</label>
                        <input disabled type="text" name="dtm_Signdate" value="@Model.SignDate" class="form-control date-picker">
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblExpireDate </label>
                        <input disabled type="text" name="dtm_Expiredate" value="@Model.Expiredate" class="form-control date-picker">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label>@Resource.lblStatus </label>
                        @Html.DropDownListFor(m => m.StatusID, new SelectList(Model.StatusList, "Key", "Value", Model.StatusID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Status--" }, { "disabled", "true" } })
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblCreatedDate </label>
                        <input type="text" disabled value="@(Model.CreatedDate != null ? Model.CreatedDate.Value.ToString("dd/MM/yyyy") :"")" class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblCreatedBy </label>
                        <input type="text" disabled value="@Model.CreatedBy" class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblLastUpdatedDate  </label>
                        <input type="text" disabled value="@(Model.UpdateDate != null ? Model.UpdateDate.Value.ToString("dd/MM/yyyy") : "")" class="form-control">
                    </div>
                    <div class="form-group col-md-4">
                        <label>Last Update By </label>
                        <input type="text" disabled value="@Model.UpdateBy" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label>@Resource.lblType </label>
                        @Html.DropDownListFor(m => m.TypeID, new SelectList(Model.TypeList, "Key", "Value", Model.TypeID), new Dictionary<string, object> { { "class", "form-control" }, { "data-placeholder", "--Type--" }, { "disabled", "true" } })
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblPrice </label>
                        <input type="number" name="mon_Price" value="@Model.Price" class="form-control" disabled>
                    </div>
                    <div class="form-group col-md-4">
                        <label>@Resource.lblCurrency </label>
                        @Html.DropDownListFor(m => m.Currency, new SelectList(Model.Curencylist, "Key", "Value", Model.Currency), new { @class = "form-control", @disabled = "true" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label>@Resource.lblNote</label>
                        <textarea disabled name="str_Note" value="@Model.Note" class="form-control" rows="3">@Model.Note</textarea>
                    </div>
                </div>
                <div class="divider"></div>
                <div class="divider"></div>
                <div class="form-group col-lg-12">
                    <div id="messageout">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                        <a onclick="goBack()" class="btn  center-block legitRipple"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> @Resource.lblBack</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            formatDatetimepicker('.date-picker', '@Resource.lblLanguage');
        });
    </script>
}